# Generated by Django 4.1 on 2023-11-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_likes_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='b04239e2-4d8c-47d8-89bd-8b746942e6ed', max_length=255),
        ),
    ]
