# Generated by Django 4.1 on 2023-11-15 19:41

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_post_id_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, validators=[blog.validators.validate_domainonly_email])),
                ('content', models.CharField(default=0, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='459cf264-61e5-4bb6-ad3a-7a04cb6a63be', max_length=255),
        ),
    ]
